### ISSUE TITLE
请问如何在merlin固件上编译使用

### ISSUE THREAD

**Issue by zhaibin18** [ptpt52/natcap#2]

**Comment by ptpt52** [comment]
参考 https://github.com/ptpt52/com.ptpt52.openwrt/tree/master/natcap

**Comment by zhaibin18** [comment]
merlin固件内核是2.6.36.4，硬件是华硕AC66U B1，是否能支持2.6的内核？

**Comment by ptpt52** [comment]
@zhaibin18 2.6 内核有点老，我需要ipset 内核特性的支持，不确定2.6有没有
建议3.10 以后的内核

**Comment by zhaibin18** [comment]
2.6内核的merlin支持ipset，但是我编译内核模块编译不过去，少很多头文件，gcc4.9和5.3都试过。
