### ISSUE TITLE
TP-Link TL-WR840N v4

### ISSUE THREAD

**Issue by hoanhtnb** [ptpt52/natcap#3]
SSID: NATCAP_DE14
Wireless is disabled or not associated
I cannot enable Wireless, please help me

`config wifi-device 'radio0'
	option type 'mac80211'
	option hwmode '11g'
	option path 'platform/10300000.wmac'
	option htmode 'HT20'
	option disabled '0'
	option country 'CN'
	option txpower '20'
	option channel 'auto'

config wifi-iface
	option device 'radio0'
	option network 'lan'
	option mode 'ap'
	option ssid 'NATCAP_DE14'
	option encryption 'psk2'
	option wpa_group_rekey '0'
	option wpa_pair_rekey '0'
	option wpa_master_rekey '0'
	option key '88888888'
`
![2017-12-13 01_33_25-natcap - wireless - luci](https://user-images.githubusercontent.com/13073010/33901913-e1842ce0-dfa5-11e7-92f8-003142afcc8b.png)

**Comment by ptpt52** [comment]
try set the channel to fixed number i.e. 7
