### ISSUE TITLE
Using in routers

### ISSUE THREAD

**Issue by kfur** [ptpt52/natcap#4]
Thanks for sharing your code but
Can you provide some more info how to use it ?

**Comment by kfur** [comment]
i mean about configuration and running it in router.

**Comment by ptpt52** [comment]
hi
I offer a natcap routing service for a fee (Only need to charge USD 35/year/device).
For most routers you can download firmware from here.

But how to use it technically, you can see the README docs.
it can be run on your Ubuntu system as client or server

**Comment by kfur** [comment]
Thanks!
Will look at x-wrt.
